version: '3.8'

services:
  # Base de données PostgreSQL
  postgres:
    image: postgres:15
    container_name: inventory_postgres
    environment:
      POSTGRES_DB: InventoryDB_Dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inventory_network

  # API Inventory Microservice
  inventory_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=InventoryDB_Dev;Username=postgres;Password=password
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - inventory_network
    restart: unless-stopped

  # pgAdmin pour la gestion de la base de données (optionnel)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: inventory_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@inventory.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - inventory_network

volumes:
  postgres_data:

networks:
  inventory_network:
    driver: bridge

